# Generated by Django 5.1.4 on 2025-02-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_categoria_fornecedor_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=None, upload_to='', verbose_name='imagem do produto'),
        ),
    ]
